### ISSUE TITLE
Waiting on dead PRs

### ISSUE THREAD

**Issue by aaossa** [muan/hello-world#174]
Hi guys, mainly @muan and @SubhrajyotiSen . At the moment, we have a lot of dead PRs, and by that I mean PRs where we requested changes but we have seen no response. How much time should we wait to close them? It seems reasonable to me to wait a month (from last update/response). What do you think?

**Comment by SubhrajyotiSen** [comment]
One month seems like a fair enough time

**Comment by zwirektech** [comment]
I'd like to share my view on this issue.
Last year I've started my journey with git. I'm a user, not a coder, but I always try to do things right. I've read manual, tutorials, etc. I've spent hours reading, learning and testing it on my local debian. Finaly I've come here. 
It was one of the biggest disappointments ever when I've made my first PR and... nothing happend. I've waited an hour, two hours and nothing happend yet... 
When you are excited with your learnig progress, you are eager to go on, it is like getting a flat tire...
Today of course I understand how It works, but at that time the workflow which is behind all these commits wasn't clear.
I think most of these dead PRs may have the same source. Someone wanted to do something... but gave up because of time delay or additional requirements to the commits he/she has done. Believe me, it is not that clear at the begining that someone has to review such a PR and what logic is in the git workflow.

I'm sorry that I don't give you a good solution here, but I think most people already working with git may not realize the beginner's confusion. Perhaps making the required tasks as simple as possible would be a good idea.

I'd like to thank you all @muan @aaossa @SubhrajyotiSen for the job you have done to help me understand the basics of git.
Especially @SubhrajyotiSen for [the detailed comment](https://github.com/muan/hello-world/pull/90#issuecomment-295851817) on my first PR.

**Comment by muan** [comment]
I think one month is reasonable time. We can add a bot to close stale PRs after one month. 

At the same time I think it might be worth doing another ping perhaps 2 weeks after the initial request change. Again we might be able to use a bot to do this. Bot can comment with something friendly like 

```
Looks like a maintainer has requested change on your pull request. Now we need you to make some changes so we can review this pull request again. These links might be helpful:

- [What's my branch]()
- [How to make changes on a branch]()
...

Please feel free to comment if the requested changes weren't clear or if you need help to proceed.
```

---

Thanks @aaossa @SubhrajyotiSen for your continued work on this repo! I'll clear out some of the issues that are waiting on me asap. 🙇‍♀️

**Comment by aaossa** [comment]
That sounds good to me 🙌 Is there any simple service to create that bot or should we create a custom one? I'm gonna try to find some possible solutions. Should we ping the current "dead PRs" manually in the meantime?

**Comment by SubhrajyotiSen** [comment]
I will try making the bot once I get some free time.
